[tool.poetry]
name = "pyplexos"
version = "0.3.0"
description = ""
authors = ["faso <bastidas.felipe@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
polars = "^0.20.2"
duckdb = "^0.9.2"
pydantic = "^2.5.3"
pydantic-xml = "^2.7.0"
numpy = "^1.26.2"
lxml = "^5.1.0"
pyarrow = "^15.0.0"
streamlit = "^1.31.0"
duckdb-engine = "^0.11.1"
sqlalchemy-access = "^2.0.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.9"
mypy = "^1.8.0"
ipykernel = "^6.29.3"
pytest = "^8.1.1"

[tool.mypy]
plugins = [
  "pydantic.mypy"
]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "pyarrow",
  "pyarrow.parquet"
]
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.mypy-pyarrow]
follow_imports = false
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
